# Generated by Django 3.1.2 on 2020-10-25 01:12

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('minPrice', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('maxPrice', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('availabilityHour', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
            ],
        ),
    ]
