# Generated by Django 3.1.2 on 2020-11-12 04:26

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_delete_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='budget',
            field=models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='isBuyer',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='profile',
            name='spent',
            field=models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=10),
        ),
    ]
