# Generated by Django 3.1.2 on 2020-11-21 03:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Biddings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Bidding_Date', models.DateTimeField(default=datetime.datetime(2020, 11, 20, 21, 44, 33, 813064))),
                ('Week_Number', models.IntegerField(default=1)),
                ('Buyer_Id', models.IntegerField(default=1)),
                ('Price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('Hours', models.IntegerField(default=0)),
                ('Item_Id', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'Biddings',
                # 'managed': False,
                # Testing
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Week_Number', models.IntegerField(default=1)),
                ('Min_Price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('Max_Price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('Total_Availibility', models.IntegerField(default=0)),
                ('Remaining_Availibility', models.IntegerField(default=0)),
                ('Start_Date', models.DateTimeField(default=datetime.datetime(2020, 11, 20, 21, 44, 33, 812637))),
                ('End_Date', models.DateTimeField(default=datetime.datetime(2020, 11, 20, 21, 44, 33, 812659))),
                ('Post_Date', models.DateTimeField(default=datetime.datetime(2020, 11, 20, 21, 44, 33, 812672))),
            ],
            options={
                'db_table': 'Items',
                # 'managed': False,
                # Testing
                'managed': True,
            },
        ),
    ]
