# Generated by Django 3.1.3 on 2020-11-07 06:33

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='Bidding_Date',
            field=models.TextField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='seller',
            name='Buyer_Id',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='seller',
            name='End_Date',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='seller',
            name='Hours',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='seller',
            name='Max_Price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
        migrations.AddField(
            model_name='seller',
            name='Min_Price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
        migrations.AddField(
            model_name='seller',
            name='Post_Date',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='seller',
            name='Price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
        migrations.AddField(
            model_name='seller',
            name='Spent',
            field=models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=5, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='seller',
            name='Start_Date',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='seller',
            name='Total_Availibility',
            field=models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=5, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='seller',
            name='Total_Budget',
            field=models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=5, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='seller',
            name='User_Id',
            field=models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=5, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='seller',
            name='Week_Number',
            field=models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=5, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
