# Generated by Django 3.1.3 on 2020-11-07 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0002_auto_20201107_0033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seller',
            name='availabilityHour',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='currentPrice',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='dateRange',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='horizon',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='maxPrice',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='minPrice',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='remainedHour',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='sellerName',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='weekNumber',
        ),
    ]
