# Generated by Django 3.1.3 on 2020-11-08 02:10

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0003_auto_20201107_0044'),
    ]

    operations = [
        migrations.CreateModel(
            name='Biddings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Bidding_Date', models.TextField(blank=True, max_length=20)),
                ('Week_Number', models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=5, validators=[django.core.validators.MinValueValidator(1)])),
                ('Buyer_Id', models.TextField(blank=True, max_length=100)),
                ('Price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('Hours', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('User_Id', models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=5, validators=[django.core.validators.MinValueValidator(1)])),
                ('Total_Budget', models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=5, validators=[django.core.validators.MinValueValidator(1)])),
                ('Spent', models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=5, validators=[django.core.validators.MinValueValidator(1)])),
            ],
            options={
                'db_table': 'Biddings',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Buyers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Bidding_Date', models.TextField(blank=True, max_length=20)),
                ('Week_Number', models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=5, validators=[django.core.validators.MinValueValidator(1)])),
                ('Buyer_Id', models.TextField(blank=True, max_length=100)),
            ],
            options={
                'db_table': 'Buyers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Week_Number', models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=5, validators=[django.core.validators.MinValueValidator(1)])),
                ('Min_Price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('Max_Price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('Start_Date', models.TextField(blank=True, max_length=100)),
                ('End_Date', models.TextField(blank=True, max_length=100)),
                ('Total_Availibility', models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=5, validators=[django.core.validators.MinValueValidator(1)])),
                ('Post_Date', models.TextField(blank=True, max_length=100)),
            ],
            options={
                'db_table': 'Items',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Seller',
        ),
    ]
