# Generated by Django 3.1.2 on 2020-11-12 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0004_auto_20201107_2010'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Buyers',
        ),
    ]
