# Generated by Django 3.1.2 on 2020-11-12 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0006_buyers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Buyers',
        ),
    ]
