# Generated by Django 3.1.2 on 2020-10-25 06:38

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0006_seller_horizon'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='weekNumber',
            field=models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=5),
        ),
    ]
