# Generated by Django 3.1.2 on 2020-10-30 04:57

import django.contrib.postgres.fields.ranges
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0008_auto_20201026_0622'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='dateRange',
            field=django.contrib.postgres.fields.ranges.DateRangeField(default=0),
        ),
    ]
