# Generated by Django 3.1.2 on 2020-10-24 19:37

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_post_minprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='availabilityHour',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5),
        ),
        migrations.AddField(
            model_name='post',
            name='maxPrice',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5),
        ),
    ]
