# Generated by Django 3.1.2 on 2020-10-25 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_auto_20201024_1937'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='availabilityHour',
        ),
        migrations.RemoveField(
            model_name='post',
            name='maxPrice',
        ),
        migrations.RemoveField(
            model_name='post',
            name='minPrice',
        ),
    ]
